package com.cware.ai.inference;

public enum AiRetryReason {
    CERTAIN_FALSE, MISSING_OPTION_MAPPING, UNKNOWN_OPTION_ID, INVALID_PURCHASE_OPTION,
    DUPLICATE_MAPPING, EMPTY_VALUE, INVALID_RESPONSE, LOW_CONFIDENCE
}
